"""
This is a setup.py script generated by py2applet
0
Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
APP_NAME = "PyManage"
DATA_FILES = []
OPTIONS = {
    'iconfile': 'app.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Making Sandwiches",
        'CFBundleIdentifier': "com.metachris.osx.sandwich",
        'CFBundleVersion': "0.0.1-alpha",
        'CFBundleShortVersionString': "0.0.1-alpha",
        'NSHumanReadableCopyright': u"Copyright © 2022, Owen Cramer, All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
